### PR TITLE
Use absolute std::result::Result in ramhorns-derive to avoid import clash

### LINKED ISSUE #37: (macro-hygiene) ramhorn derive codegen clashes with syn::Result
Hi @maciejhirsz 

Thank you for this library!

While using `ramhorns` in my project: I have a use case where I need to use both `syn` and `ramhorn` together.

Following is the minimal reproducible example:

```rust

use syn::Result;

use ramhorns::{Content};

#[derive(Content)]
struct Post<'a> {
    title: &'a str
}

```

But, On running `cargo build`, I get the following error:
```bash
error[E0107]: wrong number of type arguments: expected 1, found 2
  --> src/main.rs:53:10
   |
53 | #[derive(Content)]
   |          ^^^^^^^ unexpected type argument
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error; 7 warnings emitted

For more information about this error, try `rustc --explain E0107`.
```

From what i understand, The code generated by `ramhorn-derive` generates `Result<...>` on `Content`'s traits methods and that clashes with syn::Result. And as you can see the error message is also misleading.

What's the best way to solve this? I could alias my import of syn, but consider a larger project which imports ramhorn and derive and also has a `syn::Result` imported already, they might not know where to look for this error. As my example was small, I was able remove code incrementally and figured this out.

### PR DESCRIPTION
**Pull request by creativcoder**
Fixes #37

### CODE REVIEW

File: ramhorns-derive/src/lib.rs [hunk 1]
```diff
@@ -84,7 +84,7 @@ pub fn content_derive(input: TokenStream) -> TokenStream {
             let mut rename = None;
             let mut skip = false;
 
-            let mut parse_attr = |attr: &Attribute| -> Result<(), Error> {
+            let mut parse_attr = |attr: &Attribute| -> std::result::Result<(), Error> {
```
Comment (maciejhirsz) [inline ramhorns-derive/src/lib.rs:87]: This `Result` is not part of the output token stream, so there is no need to change anything on this line :)

Comment (creativcoder) [reply ramhorns-derive/src/lib.rs]: Ah right, that was search and replace. Reverted :)

**Review by maciejhirsz — APPROVED** [review]
